
# 由于所有用户、群组信息都使用同一个类TXUser表示，
# 使用这个值表示其确切类型。适用于tx、qq两种协议。
USER_TYPE_UNKNOWN = 0
USER_TYPE_USER = 1
USER_TYPE_GROUP = 2
USER_TYPE_SESSION = 3
USER_TYPE_DISCUS = 4
USER_TYPE_SUBSCRIBE = 5


CHAT_TYPE_NONE = USER_TYPE_UNKNOWN
CHAT_TYPE_U2U = USER_TYPE_USER
CHAT_TYPE_QUN = USER_TYPE_GROUP
CHAT_TYPE_DISCUS = USER_TYPE_DISCUS
CHAT_TYPE_SESS = USER_TYPE_SESSION
